/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WinnersRouteImport } from './routes/winners'
import { Route as LiveDrawsRouteImport } from './routes/live-draws'
import { Route as FreePostalEntryRouteImport } from './routes/free-postal-entry'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompetitionsIndexRouteImport } from './routes/competitions.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CompetitionsSlugRouteImport } from './routes/competitions.$slug'
import { Route as AdminCompetitionsNewRouteImport } from './routes/admin.competitions.new'

const WinnersRoute = WinnersRouteImport.update({
  id: '/winners',
  path: '/winners',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveDrawsRoute = LiveDrawsRouteImport.update({
  id: '/live-draws',
  path: '/live-draws',
  getParentRoute: () => rootRouteImport,
} as any)
const FreePostalEntryRoute = FreePostalEntryRouteImport.update({
  id: '/free-postal-entry',
  path: '/free-postal-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsIndexRoute = CompetitionsIndexRouteImport.update({
  id: '/competitions/',
  path: '/competitions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsSlugRoute = CompetitionsSlugRouteImport.update({
  id: '/competitions/$slug',
  path: '/competitions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompetitionsNewRoute = AdminCompetitionsNewRouteImport.update({
  id: '/admin/competitions/new',
  path: '/admin/competitions/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/free-postal-entry': typeof FreePostalEntryRoute
  '/live-draws': typeof LiveDrawsRoute
  '/winners': typeof WinnersRoute
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/competitions/': typeof CompetitionsIndexRoute
  '/admin/competitions/new': typeof AdminCompetitionsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/free-postal-entry': typeof FreePostalEntryRoute
  '/live-draws': typeof LiveDrawsRoute
  '/winners': typeof WinnersRoute
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/competitions': typeof CompetitionsIndexRoute
  '/admin/competitions/new': typeof AdminCompetitionsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/free-postal-entry': typeof FreePostalEntryRoute
  '/live-draws': typeof LiveDrawsRoute
  '/winners': typeof WinnersRoute
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/competitions/': typeof CompetitionsIndexRoute
  '/admin/competitions/new': typeof AdminCompetitionsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/free-postal-entry'
    | '/live-draws'
    | '/winners'
    | '/competitions/$slug'
    | '/admin/'
    | '/competitions/'
    | '/admin/competitions/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/free-postal-entry'
    | '/live-draws'
    | '/winners'
    | '/competitions/$slug'
    | '/admin'
    | '/competitions'
    | '/admin/competitions/new'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/free-postal-entry'
    | '/live-draws'
    | '/winners'
    | '/competitions/$slug'
    | '/admin/'
    | '/competitions/'
    | '/admin/competitions/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  FreePostalEntryRoute: typeof FreePostalEntryRoute
  LiveDrawsRoute: typeof LiveDrawsRoute
  WinnersRoute: typeof WinnersRoute
  CompetitionsSlugRoute: typeof CompetitionsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CompetitionsIndexRoute: typeof CompetitionsIndexRoute
  AdminCompetitionsNewRoute: typeof AdminCompetitionsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/winners': {
      id: '/winners'
      path: '/winners'
      fullPath: '/winners'
      preLoaderRoute: typeof WinnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-draws': {
      id: '/live-draws'
      path: '/live-draws'
      fullPath: '/live-draws'
      preLoaderRoute: typeof LiveDrawsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-postal-entry': {
      id: '/free-postal-entry'
      path: '/free-postal-entry'
      fullPath: '/free-postal-entry'
      preLoaderRoute: typeof FreePostalEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions/': {
      id: '/competitions/'
      path: '/competitions'
      fullPath: '/competitions/'
      preLoaderRoute: typeof CompetitionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions/$slug': {
      id: '/competitions/$slug'
      path: '/competitions/$slug'
      fullPath: '/competitions/$slug'
      preLoaderRoute: typeof CompetitionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/competitions/new': {
      id: '/admin/competitions/new'
      path: '/admin/competitions/new'
      fullPath: '/admin/competitions/new'
      preLoaderRoute: typeof AdminCompetitionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  FreePostalEntryRoute: FreePostalEntryRoute,
  LiveDrawsRoute: LiveDrawsRoute,
  WinnersRoute: WinnersRoute,
  CompetitionsSlugRoute: CompetitionsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  CompetitionsIndexRoute: CompetitionsIndexRoute,
  AdminCompetitionsNewRoute: AdminCompetitionsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
