/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WinnersRouteImport } from './routes/winners'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ResponsiblePlayRouteImport } from './routes/responsible-play'
import { Route as PromiseRouteImport } from './routes/promise'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PastDrawsRouteImport } from './routes/past-draws'
import { Route as OddsRouteImport } from './routes/odds'
import { Route as NextDropRouteImport } from './routes/next-drop'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as HowEntryWorksRouteImport } from './routes/how-entry-works'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DrawDayRouteImport } from './routes/draw-day'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompetitionsIndexRouteImport } from './routes/competitions.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SlipsIdRouteImport } from './routes/slips.$id'
import { Route as DevCompcardRouteImport } from './routes/dev.compcard'
import { Route as CompetitionsSlugRouteImport } from './routes/competitions.$slug'
import { Route as AdminQuestionsRouteImport } from './routes/admin.questions'
import { Route as AdminQuestionPerformanceRouteImport } from './routes/admin.question-performance'
import { Route as AdminErrorsRouteImport } from './routes/admin.errors'
import { Route as DrawsIdVerifyRouteImport } from './routes/draws.$id.verify'
import { Route as DrawsIdRevealRouteImport } from './routes/draws.$id.reveal'
import { Route as ApiPublicVerifyDrawRouteImport } from './routes/api/public/verify-draw'
import { Route as AdminCompetitionsNewRouteImport } from './routes/admin.competitions.new'

const WinnersRoute = WinnersRouteImport.update({
  id: '/winners',
  path: '/winners',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsiblePlayRoute = ResponsiblePlayRouteImport.update({
  id: '/responsible-play',
  path: '/responsible-play',
  getParentRoute: () => rootRouteImport,
} as any)
const PromiseRoute = PromiseRouteImport.update({
  id: '/promise',
  path: '/promise',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PastDrawsRoute = PastDrawsRouteImport.update({
  id: '/past-draws',
  path: '/past-draws',
  getParentRoute: () => rootRouteImport,
} as any)
const OddsRoute = OddsRouteImport.update({
  id: '/odds',
  path: '/odds',
  getParentRoute: () => rootRouteImport,
} as any)
const NextDropRoute = NextDropRouteImport.update({
  id: '/next-drop',
  path: '/next-drop',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const HowEntryWorksRoute = HowEntryWorksRouteImport.update({
  id: '/how-entry-works',
  path: '/how-entry-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawDayRoute = DrawDayRouteImport.update({
  id: '/draw-day',
  path: '/draw-day',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsIndexRoute = CompetitionsIndexRouteImport.update({
  id: '/competitions/',
  path: '/competitions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlipsIdRoute = SlipsIdRouteImport.update({
  id: '/slips/$id',
  path: '/slips/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DevCompcardRoute = DevCompcardRouteImport.update({
  id: '/dev/compcard',
  path: '/dev/compcard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsSlugRoute = CompetitionsSlugRouteImport.update({
  id: '/competitions/$slug',
  path: '/competitions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/admin/questions',
  path: '/admin/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuestionPerformanceRoute =
  AdminQuestionPerformanceRouteImport.update({
    id: '/admin/question-performance',
    path: '/admin/question-performance',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminErrorsRoute = AdminErrorsRouteImport.update({
  id: '/admin/errors',
  path: '/admin/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawsIdVerifyRoute = DrawsIdVerifyRouteImport.update({
  id: '/draws/$id/verify',
  path: '/draws/$id/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawsIdRevealRoute = DrawsIdRevealRouteImport.update({
  id: '/draws/$id/reveal',
  path: '/draws/$id/reveal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVerifyDrawRoute = ApiPublicVerifyDrawRouteImport.update({
  id: '/api/public/verify-draw',
  path: '/api/public/verify-draw',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompetitionsNewRoute = AdminCompetitionsNewRouteImport.update({
  id: '/admin/competitions/new',
  path: '/admin/competitions/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/draw-day': typeof DrawDayRoute
  '/faq': typeof FaqRoute
  '/how-entry-works': typeof HowEntryWorksRoute
  '/how-it-works': typeof HowItWorksRoute
  '/next-drop': typeof NextDropRoute
  '/odds': typeof OddsRoute
  '/past-draws': typeof PastDrawsRoute
  '/privacy': typeof PrivacyRoute
  '/promise': typeof PromiseRoute
  '/responsible-play': typeof ResponsiblePlayRoute
  '/results': typeof ResultsRoute
  '/terms': typeof TermsRoute
  '/transparency': typeof TransparencyRoute
  '/verify': typeof VerifyRoute
  '/winners': typeof WinnersRoute
  '/admin/errors': typeof AdminErrorsRoute
  '/admin/question-performance': typeof AdminQuestionPerformanceRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/dev/compcard': typeof DevCompcardRoute
  '/slips/$id': typeof SlipsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/competitions/': typeof CompetitionsIndexRoute
  '/admin/competitions/new': typeof AdminCompetitionsNewRoute
  '/api/public/verify-draw': typeof ApiPublicVerifyDrawRoute
  '/draws/$id/reveal': typeof DrawsIdRevealRoute
  '/draws/$id/verify': typeof DrawsIdVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/draw-day': typeof DrawDayRoute
  '/faq': typeof FaqRoute
  '/how-entry-works': typeof HowEntryWorksRoute
  '/how-it-works': typeof HowItWorksRoute
  '/next-drop': typeof NextDropRoute
  '/odds': typeof OddsRoute
  '/past-draws': typeof PastDrawsRoute
  '/privacy': typeof PrivacyRoute
  '/promise': typeof PromiseRoute
  '/responsible-play': typeof ResponsiblePlayRoute
  '/results': typeof ResultsRoute
  '/terms': typeof TermsRoute
  '/transparency': typeof TransparencyRoute
  '/verify': typeof VerifyRoute
  '/winners': typeof WinnersRoute
  '/admin/errors': typeof AdminErrorsRoute
  '/admin/question-performance': typeof AdminQuestionPerformanceRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/dev/compcard': typeof DevCompcardRoute
  '/slips/$id': typeof SlipsIdRoute
  '/admin': typeof AdminIndexRoute
  '/competitions': typeof CompetitionsIndexRoute
  '/admin/competitions/new': typeof AdminCompetitionsNewRoute
  '/api/public/verify-draw': typeof ApiPublicVerifyDrawRoute
  '/draws/$id/reveal': typeof DrawsIdRevealRoute
  '/draws/$id/verify': typeof DrawsIdVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/draw-day': typeof DrawDayRoute
  '/faq': typeof FaqRoute
  '/how-entry-works': typeof HowEntryWorksRoute
  '/how-it-works': typeof HowItWorksRoute
  '/next-drop': typeof NextDropRoute
  '/odds': typeof OddsRoute
  '/past-draws': typeof PastDrawsRoute
  '/privacy': typeof PrivacyRoute
  '/promise': typeof PromiseRoute
  '/responsible-play': typeof ResponsiblePlayRoute
  '/results': typeof ResultsRoute
  '/terms': typeof TermsRoute
  '/transparency': typeof TransparencyRoute
  '/verify': typeof VerifyRoute
  '/winners': typeof WinnersRoute
  '/admin/errors': typeof AdminErrorsRoute
  '/admin/question-performance': typeof AdminQuestionPerformanceRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/dev/compcard': typeof DevCompcardRoute
  '/slips/$id': typeof SlipsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/competitions/': typeof CompetitionsIndexRoute
  '/admin/competitions/new': typeof AdminCompetitionsNewRoute
  '/api/public/verify-draw': typeof ApiPublicVerifyDrawRoute
  '/draws/$id/reveal': typeof DrawsIdRevealRoute
  '/draws/$id/verify': typeof DrawsIdVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/checkout'
    | '/contact'
    | '/demo'
    | '/draw-day'
    | '/faq'
    | '/how-entry-works'
    | '/how-it-works'
    | '/next-drop'
    | '/odds'
    | '/past-draws'
    | '/privacy'
    | '/promise'
    | '/responsible-play'
    | '/results'
    | '/terms'
    | '/transparency'
    | '/verify'
    | '/winners'
    | '/admin/errors'
    | '/admin/question-performance'
    | '/admin/questions'
    | '/competitions/$slug'
    | '/dev/compcard'
    | '/slips/$id'
    | '/admin/'
    | '/competitions/'
    | '/admin/competitions/new'
    | '/api/public/verify-draw'
    | '/draws/$id/reveal'
    | '/draws/$id/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/checkout'
    | '/contact'
    | '/demo'
    | '/draw-day'
    | '/faq'
    | '/how-entry-works'
    | '/how-it-works'
    | '/next-drop'
    | '/odds'
    | '/past-draws'
    | '/privacy'
    | '/promise'
    | '/responsible-play'
    | '/results'
    | '/terms'
    | '/transparency'
    | '/verify'
    | '/winners'
    | '/admin/errors'
    | '/admin/question-performance'
    | '/admin/questions'
    | '/competitions/$slug'
    | '/dev/compcard'
    | '/slips/$id'
    | '/admin'
    | '/competitions'
    | '/admin/competitions/new'
    | '/api/public/verify-draw'
    | '/draws/$id/reveal'
    | '/draws/$id/verify'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/checkout'
    | '/contact'
    | '/demo'
    | '/draw-day'
    | '/faq'
    | '/how-entry-works'
    | '/how-it-works'
    | '/next-drop'
    | '/odds'
    | '/past-draws'
    | '/privacy'
    | '/promise'
    | '/responsible-play'
    | '/results'
    | '/terms'
    | '/transparency'
    | '/verify'
    | '/winners'
    | '/admin/errors'
    | '/admin/question-performance'
    | '/admin/questions'
    | '/competitions/$slug'
    | '/dev/compcard'
    | '/slips/$id'
    | '/admin/'
    | '/competitions/'
    | '/admin/competitions/new'
    | '/api/public/verify-draw'
    | '/draws/$id/reveal'
    | '/draws/$id/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRoute
  DrawDayRoute: typeof DrawDayRoute
  FaqRoute: typeof FaqRoute
  HowEntryWorksRoute: typeof HowEntryWorksRoute
  HowItWorksRoute: typeof HowItWorksRoute
  NextDropRoute: typeof NextDropRoute
  OddsRoute: typeof OddsRoute
  PastDrawsRoute: typeof PastDrawsRoute
  PrivacyRoute: typeof PrivacyRoute
  PromiseRoute: typeof PromiseRoute
  ResponsiblePlayRoute: typeof ResponsiblePlayRoute
  ResultsRoute: typeof ResultsRoute
  TermsRoute: typeof TermsRoute
  TransparencyRoute: typeof TransparencyRoute
  VerifyRoute: typeof VerifyRoute
  WinnersRoute: typeof WinnersRoute
  AdminErrorsRoute: typeof AdminErrorsRoute
  AdminQuestionPerformanceRoute: typeof AdminQuestionPerformanceRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  CompetitionsSlugRoute: typeof CompetitionsSlugRoute
  DevCompcardRoute: typeof DevCompcardRoute
  SlipsIdRoute: typeof SlipsIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CompetitionsIndexRoute: typeof CompetitionsIndexRoute
  AdminCompetitionsNewRoute: typeof AdminCompetitionsNewRoute
  ApiPublicVerifyDrawRoute: typeof ApiPublicVerifyDrawRoute
  DrawsIdRevealRoute: typeof DrawsIdRevealRoute
  DrawsIdVerifyRoute: typeof DrawsIdVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/winners': {
      id: '/winners'
      path: '/winners'
      fullPath: '/winners'
      preLoaderRoute: typeof WinnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsible-play': {
      id: '/responsible-play'
      path: '/responsible-play'
      fullPath: '/responsible-play'
      preLoaderRoute: typeof ResponsiblePlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promise': {
      id: '/promise'
      path: '/promise'
      fullPath: '/promise'
      preLoaderRoute: typeof PromiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/past-draws': {
      id: '/past-draws'
      path: '/past-draws'
      fullPath: '/past-draws'
      preLoaderRoute: typeof PastDrawsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odds': {
      id: '/odds'
      path: '/odds'
      fullPath: '/odds'
      preLoaderRoute: typeof OddsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/next-drop': {
      id: '/next-drop'
      path: '/next-drop'
      fullPath: '/next-drop'
      preLoaderRoute: typeof NextDropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-entry-works': {
      id: '/how-entry-works'
      path: '/how-entry-works'
      fullPath: '/how-entry-works'
      preLoaderRoute: typeof HowEntryWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draw-day': {
      id: '/draw-day'
      path: '/draw-day'
      fullPath: '/draw-day'
      preLoaderRoute: typeof DrawDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions/': {
      id: '/competitions/'
      path: '/competitions'
      fullPath: '/competitions/'
      preLoaderRoute: typeof CompetitionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slips/$id': {
      id: '/slips/$id'
      path: '/slips/$id'
      fullPath: '/slips/$id'
      preLoaderRoute: typeof SlipsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/compcard': {
      id: '/dev/compcard'
      path: '/dev/compcard'
      fullPath: '/dev/compcard'
      preLoaderRoute: typeof DevCompcardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions/$slug': {
      id: '/competitions/$slug'
      path: '/competitions/$slug'
      fullPath: '/competitions/$slug'
      preLoaderRoute: typeof CompetitionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/admin/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/question-performance': {
      id: '/admin/question-performance'
      path: '/admin/question-performance'
      fullPath: '/admin/question-performance'
      preLoaderRoute: typeof AdminQuestionPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/errors': {
      id: '/admin/errors'
      path: '/admin/errors'
      fullPath: '/admin/errors'
      preLoaderRoute: typeof AdminErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draws/$id/verify': {
      id: '/draws/$id/verify'
      path: '/draws/$id/verify'
      fullPath: '/draws/$id/verify'
      preLoaderRoute: typeof DrawsIdVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draws/$id/reveal': {
      id: '/draws/$id/reveal'
      path: '/draws/$id/reveal'
      fullPath: '/draws/$id/reveal'
      preLoaderRoute: typeof DrawsIdRevealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verify-draw': {
      id: '/api/public/verify-draw'
      path: '/api/public/verify-draw'
      fullPath: '/api/public/verify-draw'
      preLoaderRoute: typeof ApiPublicVerifyDrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/competitions/new': {
      id: '/admin/competitions/new'
      path: '/admin/competitions/new'
      fullPath: '/admin/competitions/new'
      preLoaderRoute: typeof AdminCompetitionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRoute,
  DrawDayRoute: DrawDayRoute,
  FaqRoute: FaqRoute,
  HowEntryWorksRoute: HowEntryWorksRoute,
  HowItWorksRoute: HowItWorksRoute,
  NextDropRoute: NextDropRoute,
  OddsRoute: OddsRoute,
  PastDrawsRoute: PastDrawsRoute,
  PrivacyRoute: PrivacyRoute,
  PromiseRoute: PromiseRoute,
  ResponsiblePlayRoute: ResponsiblePlayRoute,
  ResultsRoute: ResultsRoute,
  TermsRoute: TermsRoute,
  TransparencyRoute: TransparencyRoute,
  VerifyRoute: VerifyRoute,
  WinnersRoute: WinnersRoute,
  AdminErrorsRoute: AdminErrorsRoute,
  AdminQuestionPerformanceRoute: AdminQuestionPerformanceRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  CompetitionsSlugRoute: CompetitionsSlugRoute,
  DevCompcardRoute: DevCompcardRoute,
  SlipsIdRoute: SlipsIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  CompetitionsIndexRoute: CompetitionsIndexRoute,
  AdminCompetitionsNewRoute: AdminCompetitionsNewRoute,
  ApiPublicVerifyDrawRoute: ApiPublicVerifyDrawRoute,
  DrawsIdRevealRoute: DrawsIdRevealRoute,
  DrawsIdVerifyRoute: DrawsIdVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
